services:
  laravel:
    build:
      context: ./packages/laravel
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    image: sail-8.4/app
    container_name: ${PROJECT_NAME}-laravel
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./packages/laravel:/var/www/html
    networks:
      - sail
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:17
    ports:
      - "5432:5432"
    container_name: ${PROJECT_NAME}-pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    volumes:
      - sail-pgsql:/var/lib/postgresql/data
    networks:
      - sail

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    volumes:
      - sail-redis:/data
    networks:
      - sail

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PROJECT_NAME}-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - ./pgadmin/pgpass:/pgadmin4/pgpass
    depends_on:
      - pgsql
    networks:
      - sail

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ${PROJECT_NAME}-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
