version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./packages/react-app/build:/usr/share/nginx/html
    depends_on:
      - react-app
      - laravel
    networks:
      - sail

  react-app:
    build:
      context: ./packages/react-app
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}-react-app
    restart: unless-stopped
    volumes:
      - ./packages/react-app:/app
      - /app/node_modules
    networks:
      - sail

  laravel:
    build:
      context: ./packages/laravel
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    image: sail-8.4/app
    container_name: ${PROJECT_NAME}-laravel
    restart: unless-stopped
    volumes:
      - ./packages/laravel:/var/www/html
    networks:
      - sail
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: postgres:17
    container_name: ${PROJECT_NAME}-pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
    volumes:
      - sail-pgsql:/var/lib/postgresql/data
    networks:
      - sail

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    volumes:
      - sail-redis:/data
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
